parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ApiBundle\Controller\:
        resource: '../../src/ApiBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    api.email:
        class: ApiBundle\Utils\Mailer
        arguments: ['@service_container']