services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ApiBundle\Controller\:
        resource: '../../src/ApiBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    api.email:
        class: ApiBundle\Model\Mailer
        arguments: ['@service_container']

    ApiBundle\Services\KontenerParametrow:
        arguments: ['@service_container']

    api.logger:
        class: Monolog\Logger
        arguments: ['@?']