services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ApiBundle\Controller\:
        resource: '../../src/ApiBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    api.email:
        class: ApiBundle\Model\Mailer
        arguments: ['@service_container']

    api.kolejki:
        class: ApiBundle\Model\RabbitMQ\Kolejka
        arguments: [
            '%queue_host%',
            '%queue_port%',
            '%queue_user%',
            '%queue_password%',
            '%queue_vhost%']
