<?php

namespace ApiBundle\Repository;

/**
 * GrupyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupyRepository extends \Doctrine\ORM\EntityRepository
{
}
