<?php

namespace ApiBundle\Repository;

/**
 * PlikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlikRepository extends \Doctrine\ORM\EntityRepository
{
}
