<?php

namespace ApiBundle\Repository;
use ApiBundle\Entity\Uzytkownik;
use ApiBundle\Exception\UzytkownikNieIstniejeException;

/**
 * UzytkownikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UzytkownikRepository extends \Doctrine\ORM\EntityRepository
{
    public function czyIstniejeTakiUzytkownik($login)
    {
        return true;
    }

    public function pobierzIdUzytkownikaPoLoginie($login, $haslo)
    {
        /**
         * @var $id Uzytkownik
         */
        $encja = $this->findOneBy(['login' => $login, 'haslo' => $haslo]);

        if(!$encja instanceof Uzytkownik){
            throw new UzytkownikNieIstniejeException();
        }

        return $encja->getId();
    }
}
